name: Python Tests

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  tests:
    name: Local Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies with Pip
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Lint with Flake8
      run: |
        # Stop the build if there are lint errors. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with Pytest
      run: |
        pytest
